coverage:
  range: 50..70
  round: down
  precision: 0
  status:
    project:
      default:
        base: auto
        threshold: 0.5
        informational: true
ignore:
  - "typed_python/compiler/type_wrappers/native_hash.py"
