version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - sphinx-apidoc -fo docs/api typed_python typed_python/*test* typed_python/*/*test*


python:
  install:
    - requirements: docs/doc_requirements.txt
