[tool.black]
line-length = 95
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.github
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.nodeenv
  | \.pytest_cache
  | typed_python.egg-info
  | build
  | dist
)/
'''
