version: 1
disable_existing_loggers: False
formatters:
    default:
        format: '[%(asctime)s] %(levelname)8s %(filename)30s:%(lineno)4s | %(message)s'

handlers:
    default:
        class: logging.StreamHandler
        level: 0  # Default Handler should apply to all levels
        formatter: default
        stream: ext://sys.stdout

root:
    level: 10  # Default level==INFO
    handlers: [default]
